/*
 * This file is generated by jOOQ.
 */
package com.example.banksystem.database.schema;


import com.example.banksystem.database.schema.tables.BankInfo;
import com.example.banksystem.database.schema.tables.BankType;
import com.example.banksystem.database.schema.tables.User;
import com.example.banksystem.database.schema.tables.UserInfo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.bank_info</code>.
     */
    public final BankInfo BANK_INFO = BankInfo.BANK_INFO;

    /**
     * The table <code>public.bank_type</code>.
     */
    public final BankType BANK_TYPE = BankType.BANK_TYPE;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>public.user_info</code>.
     */
    public final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BankInfo.BANK_INFO,
            BankType.BANK_TYPE,
            User.USER,
            UserInfo.USER_INFO
        );
    }
}
