/*
 * This file is generated by jOOQ.
 */
package com.example.banksystem.database.schema;


import com.example.banksystem.database.schema.tables.BankInfo;
import com.example.banksystem.database.schema.tables.BankType;
import com.example.banksystem.database.schema.tables.User;
import com.example.banksystem.database.schema.tables.UserInfo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bank_info</code>.
     */
    public static final BankInfo BANK_INFO = BankInfo.BANK_INFO;

    /**
     * The table <code>public.bank_type</code>.
     */
    public static final BankType BANK_TYPE = BankType.BANK_TYPE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
